name: Test Shithead Server

on:
  push:
    branches: [ "main" ]
    # paths: ["server/**"]
  pull_request:
    branches: [ "main" ]
    # paths: ["server/**"]
  
jobs:
  tests:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] 
        python-version: ["3.11"] 
    defaults:
      run:
        working-directory: ./server
        shell: bash
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - uses: snok/install-poetry@v1
      with:
        version: 1.8.5
        virtualenvs-create: true

    - run: poetry install --no-interaction

    - run: poetry run python -m black --check pyshithead/main.py pyshithead/models/common/game_manager.py pyshithead/models/game/game.py pyshithead/models/session/manager.py tests/test_alpha_api.py

    - run: poetry run python -m isort --check-only pyshithead/main.py pyshithead/models/common/game_manager.py pyshithead/models/game/game.py pyshithead/models/session/manager.py tests/test_alpha_api.py

    - run: poetry run python -m pytest --junitxml=junit/test-results-${{ matrix.python-version }}-${{ matrix.os }}.xml --cov

    - name: Upload pytest test results
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results-${{ matrix.python-version }}-${{ matrix.os }}
        path: server/junit/test-results-${{ matrix.python-version }}-${{ matrix.os }}.xml
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
